# Generated by Django 4.0.1 on 2022-01-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinmena', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='from_currency_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quote',
            name='from_currency_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quote',
            name='time_zone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quote',
            name='to_currency_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quote',
            name='to_currency_name',
            field=models.CharField(max_length=50),
        ),
    ]
